build:
  version: "2.0"

accounts:
  message: "Welcome to Bank loans related local APIs "
  contactDetails:
    name: "Yusuf Kılıç - Backend Developer"
    email: "yuzarsifkilic@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
